#服务端口
server:
  port: 8091
#服务名称
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/15369952760/springCloudServer #服务git
          search-paths: /** #配置文件所在的目录
      label: master #配置文件所在的分支
      username: 15369952760
      password: ainiwuhui555
#服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

