
server:
  port: 8091
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/15369952760/springCloudServer
          search-paths: /**
      label: master
      username: 15369952760
      password: #密码
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

